/**
 * The sample workspace a development database starts from when there is no
 * Discord server to mirror. Data only; the inserting lives in `seed.ts`.
 */

export const memberSeeds = [
  {
    name: "Alex Kim",
    displayName: "alex",
    email: "alex@acme.dev",
    avatarColor: "#5e6ad2",
    isAdmin: true,
  },
  {
    name: "Jordan Lee",
    displayName: "jordan",
    email: "jordan@acme.dev",
    avatarColor: "#26b5ce",
    isAdmin: true,
  },
  {
    name: "Sam Park",
    displayName: "sam",
    email: "sam@acme.dev",
    avatarColor: "#f2994a",
    isAdmin: false,
  },
  {
    name: "Riley Chen",
    displayName: "riley",
    email: "riley@acme.dev",
    avatarColor: "#eb5757",
    isAdmin: false,
  },
  {
    name: "Morgan Choi",
    displayName: "morgan",
    email: "morgan@acme.dev",
    avatarColor: "#27ae60",
    isAdmin: false,
  },
  {
    name: "Casey Han",
    displayName: "casey",
    email: "casey@acme.dev",
    avatarColor: "#bb87fc",
    isAdmin: false,
  },
  {
    name: "Taylor Yoon",
    displayName: "taylor",
    email: "taylor@acme.dev",
    avatarColor: "#f7c948",
    isAdmin: false,
  },
  {
    name: "Drew Oh",
    displayName: "drew",
    email: "drew@acme.dev",
    avatarColor: "#4ea7fc",
    isAdmin: false,
  },
] as const;

export const workspaceLabelSeeds = [
  { name: "Bug", color: "#eb5757" },
  { name: "Feature", color: "#bb87fc" },
  { name: "Improvement", color: "#4ea7fc" },
  { name: "Documentation", color: "#95a2b3" },
  { name: "Performance", color: "#f2c94c" },
  { name: "Security", color: "#f2994a" },
  { name: "Design", color: "#26b5ce" },
  { name: "Tech Debt", color: "#8a8f98" },
] as const;

export const projectSeeds = [
  {
    name: "Command palette v2",
    icon: "⌘",
    color: "#5e6ad2",
    status: "started",
    health: "on_track",
    description:
      "Rebuild the command palette with fuzzy search, recent actions, and nested commands.",
    startOffsetDays: -21,
    targetOffsetDays: 14,
  },
  {
    name: "Workspace analytics",
    icon: "◔",
    color: "#26b5ce",
    status: "started",
    health: "at_risk",
    description:
      "Burndown charts, scope change tracking, and velocity for the whole workspace.",
    startOffsetDays: -35,
    targetOffsetDays: 7,
  },
  {
    name: "Incident tooling",
    icon: "◉",
    color: "#eb5757",
    status: "planned",
    health: null,
    description:
      "On-call rotations, incident timelines, and postmortem templates.",
    startOffsetDays: 3,
    targetOffsetDays: 60,
  },
  {
    name: "Design system refresh",
    icon: "◆",
    color: "#f2994a",
    status: "started",
    health: "on_track",
    description:
      "New color tokens, typography scale, and component documentation.",
    startOffsetDays: -14,
    targetOffsetDays: 30,
  },
  {
    name: "Database sharding",
    icon: "▤",
    color: "#27ae60",
    status: "backlog",
    health: null,
    description:
      "Shard the issues table by workspace to keep p99 query time flat.",
    startOffsetDays: null,
    targetOffsetDays: null,
  },
  {
    name: "Mobile beta",
    icon: "▯",
    color: "#bb87fc",
    status: "completed",
    health: "on_track",
    description: "Read-only iOS and Android apps for triage on the go.",
    startOffsetDays: -90,
    targetOffsetDays: -10,
  },
] as const;

export const issueTitleSeeds = [
  "Command palette does not close on Escape when a submenu is open",
  "Add fuzzy matching to the command palette search",
  "Persist recently used commands per user",
  "Keyboard shortcut cheat sheet overlay",
  "Project burndown chart renders incorrectly for canceled issues",
  "Track scope changes after a milestone is set",
  "Velocity metric should use completed estimate, not issue count",
  "Show project progress in the sidebar",
  "On-call schedule import from PagerDuty",
  "Incident timeline should support markdown attachments",
  "Postmortem template with action items",
  "Alert grouping for repeated failures",
  "Migrate button component to new tokens",
  "Document spacing scale in the design system site",
  "Dark mode contrast audit for muted text",
  "Replace legacy icon set with the new outline set",
  "Benchmark issue list query under 10M rows",
  "Write shard key selection RFC",
  "Prototype dual-write for issues table",
  "Push notifications for assigned issues on mobile",
  "Offline queue for comments in the mobile app",
  "Issue detail page flickers when switching between issues quickly",
  "Board view drag and drop drops the card on the wrong column on Firefox",
  "Filter by label should support negation",
  "Bulk edit selected issues from the list view",
  "Estimate picker should support t-shirt sizes",
  "Snooze issue until next week",
  "Sub-issue progress bar in parent issue header",
  "Duplicate detection when creating an issue",
  "Notification when an issue I subscribe to changes state",
  "Search should index comment bodies",
  "Export project as CSV",
  "Project update reminders every Friday",
  "Milestone progress in the project header",
  "Slow initial load on the projects page",
  "Memory leak in the issue list virtualizer",
  "Add tooltip to truncated issue titles",
  "Renaming the workspace should update page titles everywhere",
  "Archive completed projects older than 90 days automatically",
  "Label colors should be editable inline",
  "Workspace settings: allow changing the issue prefix",
  "Inbox: mark all as read keyboard shortcut",
  "Sidebar sections should remember collapsed state",
  "Copy issue link with title from the context menu",
  "Show related issues in the sidebar of the issue page",
  "Blocked issues should display a warning icon in lists",
  "Support pasting images into the description editor",
      "Add 'Created by me' tab to My Issues",
] as const;

export const commentBodySeeds = [
  "I can reproduce this on main. Looking into it now.",
  "This is blocked on the tokens PR — will pick it up once that lands.",
  "Should we split this into two issues? The second half feels separate.",
  "Fixed in the latest build, please verify.",
  "Bumping priority, a customer hit this again today.",
  "Design attached in Figma, let me know if the spacing feels off.",
  "I think we can ship this without the animation and follow up later.",
  "Adding a test for the Firefox drop target math.",
] as const;
